// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDrfJQQh_YKr3JPJn6Z2ByLhhTJs_L8RQ',
    appId: '1:146766325718:web:9907f33a93a2d8438ee677',
    messagingSenderId: '146766325718',
    projectId: 'portfolio-36cd0',
    authDomain: 'portfolio-36cd0.firebaseapp.com',
    storageBucket: 'portfolio-36cd0.appspot.com',
    measurementId: 'G-M1LKR9E48D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpjBJHvfOle4-C0hkzB8fW_5TQveQlH0o',
    appId: '1:146766325718:android:426e2e7916877ec68ee677',
    messagingSenderId: '146766325718',
    projectId: 'portfolio-36cd0',
    storageBucket: 'portfolio-36cd0.appspot.com',
  );
}
